apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database/statefullset.yaml
  - persistanse/persistentvolume.yaml
  - persistanse/persistentvolumeclaim.yaml
  - Project serve v1.3/manifests/deployment.yaml
  - Project serve v1.3/manifests/service.yaml
  - Project serve v1.3/manifests/ingress.yaml
  - todo backend/manifests/deployment.yaml
  - todo backend/manifests/service.yaml
  - todo backend/manifests/secret.yaml
images:
  - name: PROJECT/IMAGE
    newName: gcr.io/dwk-gke-445811/todo-backend
  - name: PROJECT/IMAGE2
    newName: gcr.io/dwk-gke-445811/danfor/todo-app
  - name: PROJECT/IMAGE3
    newName: gcr.io/dwk-gke-445811/redis:7