apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: IMAGE1
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "200m"
            memory: "200Mi"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: log-output-redis-secrets
              key: REDIS_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: log-output-redis-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: log-output-redis-secrets
              key: REDIS_PORT