apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- database/statefullset.yaml
- project/deployment.yaml
- project/service.yaml
- project/ingress.yaml
- project/secret.yaml
- todo-backend/deployment.yaml
- todo-backend/service.yaml
- todo-backend/secret.yaml
- Deployment.yaml
- broadcaster/secret.yaml

images:
- name: PROJECT/IMAGE1
  newName: danfor1/todo-backend
  newTag: 822989e36d71f97c80484ff5b5bd31d21fc80a2f
- name: PROJECT/IMAGE2
  newName: danfor1/todo-app
  newTag: 822989e36d71f97c80484ff5b5bd31d21fc80a2f
- name: PROJECT/IMAGE4
  newName: danfor1/broadcaster
  newTag: 822989e36d71f97c80484ff5b5bd31d21fc80a2f
