apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: PROJECT/IMAGE2
        imagePullPolicy: IfNotPresent
        env:
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: frontend-redis-secrets
                    key: REDIS_PASSWORD
              - name: REDIS_HOST
                valueFrom:
                  secretKeyRef:
                    name: frontend-redis-secrets
                    key: REDIS_HOST
              - name: REDIS_PORT
                valueFrom:
                  secretKeyRef:
                    name: frontend-redis-secrets
                    key: REDIS_PORT