apiVersion: batch/v1
kind: CronJob
metadata:
  name: database-backup
spec:
  schedule: "0 0 * * *"  # Runs at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: PROJECT/IMAGE3
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: "150m"
                memory: "100Mi"
            env:
              - name: REDIS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: backup-redis-secrets
                    key: REDIS_PASSWORD
              - name: REDIS_HOST
                valueFrom:
                  secretKeyRef:
                    name: backup-redis-secrets
                    key: REDIS_HOST
              - name: REDIS_PORT
                valueFrom:
                  secretKeyRef:
                    name: backup-redis-secrets
                    key: REDIS_PORT
              - name: BUCKET_NAME
                value: "your-bucket-name"
            volumeMounts:
              - name: gcp-credentials
                mountPath: "/gcp"
                readOnly: true
          volumes:
            - name: gcp-credentials
              secret:
                secretName: gcp-credentials
                items:
                - key: key.json
                  path: credentials.json
          restartPolicy: OnFailure