apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-backend-HPA
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-backend
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50