apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: log-output
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-data
              mountPath: /data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
            claimName: timestamp-claim