apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

resources:
  - ../../base
  - manifests/job.yaml
  - manifests/secret.yaml
images:
  - name: PROJECT/IMAGE1
    newName: danfor1/todo-backend
  - name: PROJECT/IMAGE2
    newName: danfor1/todo-app
  - name: PROJECT/IMAGE3
    newName: danfor1/database-backup
  - name: PROJECT/IMAGE4
    newName: danfor1/broadcaster