name: Delete environment

on:
  delete:
    branches:
      - '*'

env: 
  PROJECT_ID: dwk-gke-445811
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.event.ref }}

jobs:
  delete-environment:
    name: Delete Kubernetes Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: Extract deleted branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Ensure branch-based namespace
        run: |-
          if [[ "$BRANCH" == "default" || "$BRANCH" == "kube-system" ]]; then
            echo "Refusing to delete critical namespace: $BRANCH"
            exit 1
          fi

      - name: Delete namespace
        run: |-
          NAMESPACE_TO_DELETE=$(echo "$BRANCH" | tr '/' '-')
          echo "Attempting to delete namespace: $NAMESPACE_TO_DELETE"
          kubectl get namespace $NAMESPACE_TO_DELETE
          kubectl delete namespace $NAMESPACE_TO_DELETE --timeout=2m || echo "Namespace $NAMESPACE_TO_DELETE does not exist"