name: Delete environment

on:
  delete:
    branches:
      - '*'

env: 
  PROJECT_ID: dwk-gke-445811
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  delete-environment:
    name: Delete Kubernetes Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate kubectl
        run: |-
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --zone $GKE_ZONE \
            --project $PROJECT_ID

      - name: Extract deleted branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Ensure branch-based namespace
        run: |-
          if [[ "$BRANCH" == "default" || "$BRANCH" == "kube-system" ]]; then
            echo "Refusing to delete critical namespace: $BRANCH"
            exit 1
          fi

      - name: Delete namespace
        run: |-
          kubectl delete namespace $BRANCH || echo "Namespace $BRANCH does not exist"