name: Build and publish application

on:
  push:
    

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push log-output
        run: |-
          docker build --tag "log-output:$GITHUB_SHA" "./Part-4/Exercise-4.07/logoutput"
          docker push "log-output:$GITHUB_SHA"

      - name: Build and push ping-pong
        run: |-
          docker build --tag "ping-pong:$GITHUB_SHA" "./Part-4/Exercise-4.07/pingpong"
          docker push "ping-pong:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update images in kustomization
        run: |-
          cd ./Part 4/Exercise 4.07
          kustomize edit set image \
            IMAGE1=log-output:$GITHUB_SHA \
            IMAGE2=ping-pong:$GITHUB_SHA

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}