name: Release application

on:
  push:

env:
  PROJECT_ID: dwk-gke-445811
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      # Build, tag, and push the first image
      - name: Build Image 1
        run: docker build --tag "gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA" "./Part 3/Exercise 3.06/todo-backend"

      - name: Push Image 1
        run: docker push "gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA"

      # Build, tag, and push the second image
      - name: Build Image 2
        run: docker build --tag "gcr.io/$PROJECT_ID/todo-app:$BRANCH-$GITHUB_SHA" "./Part 3/Exercise 3.06/Project-serve-v1.4.2"

      - name: Push Image 2
        run: docker push "gcr.io/$PROJECT_ID/todo-app:$BRANCH-$GITHUB_SHA"

      - name: Build Image 3
        run: docker build --tag "gcr.io/$PROJECT_ID/database-backup:$BRANCH-$GITHUB_SHA" "./Part 3/Exercise 3.06/backup-database"

      - name: Push Image 3
        run: docker push "gcr.io/$PROJECT_ID/database-backup:$BRANCH-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy
        run: |-
          kubectl create namespace ${GITHUB_REF#refs/heads/} || true
          kubectl config set-context --current --namespace=${GITHUB_REF#refs/heads/}
          cd "./Part 3/Exercise 3.06"
          kustomize edit set namespace ${GITHUB_REF#refs/heads/}
          kustomize edit set image \
            PROJECT/IMAGE=gcr.io/$PROJECT_ID/todo-backend:${GITHUB_REF#refs/heads/}-$GITHUB_SHA \
            PROJECT/IMAGE2=gcr.io/$PROJECT_ID/todo-app:${GITHUB_REF#refs/heads/}-$GITHUB_SHA \
            PROJECT/IMAGE3=gcr.io/$PROJECT_ID/database-backup:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/todo-backend
          kubectl rollout status deployment/todo-app
          kubectl get services -o wide